In [27]:
#Add two matrics, using for loop
a=[[1,2,3],
   [1,2,3]]
b=[[3,2,1],
   [3,2,2]]
result=[[0,0,0],
        [0,0,0]]
for i in range (len(a)):
    #print (a[i],"len of a ",len(a),"len of a[i] ", len(a[i]))
    for j in range (len(a[0])):
        result [i][j]=a[i][j]+b[i][j]
for r in result:
   print (r)


[4, 4, 4]
[4, 4, 4]
[4, 4, 5]


In [46]:
#add two matrics using list comprehension
a=[[1,2,3],
   [10,11,12],
   [3,2,1]]
b=[[1,2,3],
   [12,11,10],
   [3,2,1]]

result=[[a[i][j]+b[i][j] for j in range (len(a[0]))] for i in range (len(a))]
for r in result:
   print (r)


[2, 4, 6]
[22, 22, 22]
[6, 4, 2]


In [49]:
#add 2 matrix using numpy
import numpy as np
a=np.array([[1,2,3],
            [10,11,12],
            [3,2,1]])
b=np.array([[1,2,3],
            [12,11,10],
            [3,2,1]])
result=a+b
print(result)

[[ 2  4  6]
 [22 22 22]
 [ 6  4  2]]


In [52]:
#transpose of a matrix
import numpy as np
a=np.array([[ 2, 4, 6],
            [22, 22, 22],
            [ 6, 4, 2]])
transpose_matrix=a.transpose()
print("Transposed Matrix is ",transpose_matrix)

Transposed Matrix is  [[ 2 22  6]
 [ 4 22  4]
 [ 6 22  2]]


In [53]:
import numpy as np
a=np.array([[ 2],
            [22],
            [ 6]])
transpose_matrix=a.transpose()
print("Transposed Matrix is ",transpose_matrix)

Transposed Matrix is  [[ 2 22  6]]


In [56]:
#multiply a matrix
import numpy as np
a=np.array( [[4,9,9],
             [9,1,6],
             [9,2,3]])
b=np.array( [[2,2],
             [5,7],
             [4,4]])
result1=a@b
print(result1)

[[ 89 107]
 [ 47  49]
 [ 40  44]]


In [59]:
#remove punctuation from the string
import string
s = "learn. to. code.yay!?"
for char in string.punctuation:
    s = s.replace(char, "")
print(s)

learn to codeyay


In [61]:
#count the number of each vowels from string
sum=0
input_string="Manasa is learning"
for vow in input_string:
    if vow in "aeiou":
        sum=sum+1
print(f'Total number of vowels in the string: {sum}')
    

Total number of vowels in the string: 7
